ttcn3/syntax/ast.go
ttcn3/syntax/parser.go
ttcn3/syntax/parser_test.go

This PR only introduces an AST skeleton, because a proper (Roslyn inspired) AST implementation, requires scanner and token handling to be refactored first.

Syntax tree

---

internal/session/flock/flock.go
internal/session/storage.go

ntt respects umask when creating shared lock file. This causes `permission denied` error on shared machines. By making session files world wide writeable we have less such errors.

Make sessions world wide writeable

---

internal/session/flock/flock.go
internal/session/storage.go

The sessions files in /tmp/k3 have to be writable by any user.
Individual umask settings however prevent file being world wide
writable.
A previous fix therefore explicitly calls `os.Chmod(0666)` on all
session files. This introduced a new issue:
chmod: operation not permitted
This is because permission of a file may only be changed by its owner or
by a privileged process (see man 2 chmod for details).
This commit ignores chmod errors. Which should be safe because follow up
situation should be caught by later error checks.

Ignore chmod errors

---

cmd/k3-mcov/main.go
internal/ttcn3/parser/api.go

Extensive usage of `*` and `?` in templates causes gaps in message content
validation. A tool for detecting those gaps would help to improve test quality.
One example is worth a thousand words:
```
type record MessageA {
integer a,
integer b,
integer c
}
type record MessageB {
integer a,
integer b
}
type record MessageC {
integer a,
float f
}
...
p.receive(MessageA:{1,?,2});
p.receive(MessageA:{1,?,?});
p.receive(MessageC:{?,0.1});
...
```
In this example we have three records of which only two are covered (partially). A
report would look like this (new lines are added for better readability):
```
Module1.MessageA.a	2
Module1.MessageA.b	0
Module1.MessageA.c	1
Module1.MessageB.a	0
Module1.MessageB.b	0
Module2.MessageC.a	0
Module2.MessageC.f	1
```
The coverage of a field is reported in two …

Message coverage

---

.goreleaser.yml
cmd/k3/main.go
cmd/k3/version.go
internal/t3xf/opcode/opcode.go

People who want to use [Visual Studio Code Extension for TTCN-3](https://marketplace.visualstudio.com/items?itemName=Nokia.ttcn3) need easy access to k3 language server. Downloading pre-compiled binaries are an easy option with [Goreleaser](https://goreleaser.com/).

Prepare for first releases

---

cmd/k3/show.go
internal/ntt/env.go

`k3 show` and `ntt.Environ` will output quoted values for environment
variables.
This helps using k3 in shell scripts. Example:
. <(k3 show -- env)

Quote value of environment variables

---

internal/ttcn3/parser/parser.go

Beeing able to run ttcn3 files as script, could come in handy:
```
$ cat MyPluginTests.ttcn3 
#!k3 run -j
module MyPluginTests {
testcase Test1() ...
testcase Test2() ...
}
$ chmod +x MyPluginTests.ttcn3
$ ./MyPluginTests.ttcn3
```

Allow shebang

---

internal/ntt/env.go
internal/ntt/env_test.go

Referencing a variable multiple times, caused a recursion error. This commit removes the error message. Recursive variables will be substituted with an empty string instead.

Fix recursion error

---

internal/lsp/server_gen.go
internal/lsp/text_synchronization.go
internal/lsp/trace.go

The language server should not print errors directly to stderr, but to the language server client instead. Further it should be possible to configure log-levels.

Improve logging of language server

---

internal/lsp/definition.go
internal/lsp/general.go
internal/lsp/text_synchronization.go

The assumption all URI were `file://` failed, when using vscode remote-ssh-extension. This caused a panic from net/url package.
This commit removes all URI to path conversions.

Replace paths with URIs

---

internal/cmds/lint/error.go
internal/cmds/lint/main.go
internal/ttcn3/ast/ast.go
internal/ttcn3/ast/utils.go
internal/ttcn3/parser/parser.go

ttcn3_validator is a Nokia internal linter tool for TTCN-3. This commits
add its functionality to ntt lint tool. Available checks:
* aligned braces
* maximum number of lines of lines in behaviour bodies
* maximum cyclomatic complexity
* naming rules
* TTCN-3 tags

Add ttcn3_validator checks

---

cmd/ntt/main.go
go.mod
go.sum
internal/cmds/report/loads.go
internal/cmds/report/loads_unix.go
internal/cmds/report/main.go
internal/cmds/report/report.go
internal/ntt/ntt.go
internal/results/results.go
internal/results/results_test.go
vendor/gopkg.in/check.v1/checkers.go
vendor/modules.txt

This PR introduces a new command `report`.
`ntt report` makes use of k3s' verdic file `test_results.json` and provides various kinds of reports:
* Fancy coloured output, useful as summary (`ntt report`)
* ~~tab separated output, useful for piping into 3rd party shells scripts (`ntt report --tsv`)~~
* JUnit report for Jenkins integration (`ntt report --junit`)
* Detailed JSON output, useful for monitoring and statistics. (`ntt report --json`)
* Custom output using Go template engine. (`ntt report --template`)

Add new command report

---

cmd/ntt/main.go
cmd/ntt/show.go
internal/cmds/locate_file/\
internal/cmds/locate_file/main.go
internal/ntt/ntt.go

ntt provides a mechanism for locating source files similar to the VPATH
mechanism of GNU Make.
This commit introduces a new command locate-file to help 3rd party tools
using this feature without needing to know the exact policy.
This commit also changes the search behavior of ntt: It first looks at the
current working directory and then consults NTT_CACHE environment
variable for further lookups.

Add helper command locate-file

---

internal/lsp/completion.go

vscode has a special URI format for new, unsaved files, which is not compatible with the span package. The URI format changes to __file://__ as soon as the file is saved to the file system

No autocompletion for new, unsaved files

---

internal/fs/file.go
internal/fs/fs_test.go
internal/lsp/definition.go

This PR solves two issues:
* Files could not be read, when their paths were specified as URL
* Language Server panicked, when Goto-Definition could not read .ttcn3 file.
This PR further adds some logging and a small test to prevent future regression.

Various fixes

---

internal/env/env_test.go
internal/ntt/cli.go
internal/ntt/env.go
internal/ntt/env_test.go
internal/ntt/ntt.go

This commit replaces our custom environment handling implementation with
a port of the better known dotenv project.
It also introduces some breaking changes:
* ntt.env is evaluated before k3.env
* NTT_ prefix has a higher precedence than K3_ prefix
* all variables have to be defined up-front
* all unknown environment variables will be replaced with ""

Add new environment implementation

---

internal/cmds/list/main.go
internal/ntt/env.go
internal/ntt/manifest.go
internal/ntt/manifest_test.go
internal/ntt/ntt.go
project/env_test.go
project/project.go

This commit moves manifest file and variables handling from internal/ntt to project package.
The idea behind is to create a more data centric API for manifests. Before we can use value objects and such, we have to decouple things first.

Move some manifest code to project package

---

internal/lsp/status.go

This commit fixes the ntt.status panic when ntt.Suite.Files method returns an error.
This commit also replaces panic with a simple log message.

Fix ntt.status command

---

cmake/FindNTT.cmake

This commit removes the ttcn3_suite.json file before every configuration
step to provent getting it longer.

Always remove ttcn3_suites.json

---

internal/cmds/dump/main.go
internal/cmds/lint/main.go
internal/cmds/list/main.go
internal/cmds/run/main.go
ttcn3/ttcn3.go

This commit replaces parser calls `parser.ParseModule`,
`suite.Parse` with `ttcn3.ParseFile`.
Exceptions are the internals/lsp and internal/ntt packages. Because
internal/lsp parser calls depend on typesystem being finished. and
internal/ntt parser calls depend on internal/lsp being replaced first.
Why this change? We are working towards a more IDE-friendly parser API.
Those changes keep technical debt in check.

Use ttcn3.ParseFile

---

go.mod
go.sum
internal/cmds/report/main.go
internal/fs/utils.go
internal/lsp/commands.go
internal/lsp/server.go
runner/runner.go
vendor/github.com/acarl005/stripansi/LICENSE
vendor/github.com/acarl005/stripansi/README.md
vendor/github.com/acarl005/stripansi/stripansi.go
vendor/modules.txt

This commit moves test execution into a dedicated package. This is a
first step of making test execution asynchronous.
This commit also exports some Templates from ntt-report command for
making programmatic report generation easier.

Refactor ntt.test

---

cmd/ntt/report.go
cmd/ntt/show.go

Some errors could not be serialized into JSON format causing show to
fail.
This commit uses strings instead of an error interface.

Fix JSON output for error

---

cmd/ntt/main.go

Nokia uses a custom runner internally. This internal runner was never
called, because ntt's run command registered as soon as environment
variable `K3_40_RUN_POLICY` was not set.
This commit fixes the condition and make improves its readability to
prevent similar issues in the future.

Fix Nokia runner

---

editors.md

Not sure how long ntt can be integrated into lsp-mode. So here is a configuration guide without lsp-mode integration.

Add Emacs configuration guide

---

k3/run/run_test.go
k3/run/testdata/suite/test.ttcn3

The previous testcase `math.Test` stopped being available in T3XF file.
Background:
k3-build script did not pass imported TTCN-3 files to the compiler, but
the ntt build command did.
This caused problems ("no such module PCMDmod") when developer at Nokia
started importing k3 plugins directly.

Replace timeout test

---

cmd/ntt-mcov/main_test.go
internal/session/storage_test.go
k3/k3_test.go
k3/run/run_test.go

A testing cleanup. 
This pull request replaces `ioutil.TempDir` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := ioutil.TempDir("", "")
if err != nil {
t.Fatal(err)
}
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
```

test: use `T.TempDir` to create temporary test directory

---

k3/k3.go
k3/k3_test.go
k3/run/run_test.go
project/project.go

Some TTCN-3 libraries contain TTCN-3 files which must not included. This commit does not pass imported files to the internal Nokia compiler, but imported directories instead.
Please note, that resulting T3XF might not be complete, because current compiler only includes modules which are imported by a source file.

Pass import-directories instead of files

---

internal/lsp/general.go
internal/lsp/hover.go
internal/lsp/server_gen.go

Fixes #199
i do not understand where the testing data comes from 
the change in server_gen.go gives an error even though elsewhere it is implemented the same

Implement show hover

---

builtins/match.go
interpreter/interpreter.go
runtime/object.go

When creating a list with a specific size, NewList did not assign `runtime.Undefined` to its fields. The nil pointer caused a panic when accessed.

Fix NewList Behaviour

---

internal/results/results.go

Return an empty `results.DB` structure, when no test_result.json file is
available.
Function `results.Latest` is supposed to return an empty structure, when
no test_result.json is available. However, `json.Unmarshal` returns an
error for empty bytes slices, which is was not intended behaviour.

Fix handling missing test_result.json

---

builtins/builtins.go
interpreter/interpreter.go
interpreter/interpreter_test.go
runtime/object.go

this is my first commit to this repo.
Please check it carefully.
Changes to runtime/object.go are up for discussion - motivation for this part is in 'padding' from spec (see below)
https://www.etsi.org/deliver/etsi_es/201800_201899/20187301/04.07.01_60/es_20187301v040701p.pdf
ETSI ES 201 873-1 V4.7.1 (2015-06)
page 288
> C.1.3 Integer to bitstring
int2bit(in integer invalue, in integer length) return bitstring
This function converts a single integer value to a single bitstring value. 
The resulting string is length bits long.
For the purposes of this conversion, a bitstring shall be interpreted as a positive base 2 integer value.
The rightmost bit is least significant, the leftmost bit is the most significant. 
The bits 0 and 1 represent the decimal values 0 and 1 respectively.
If the …

adding builtin function int2bin

---

builtins/builtins.go
interpreter/interpreter_test.go

Add new function int2char and add tests for it
Function returns charstring
This function converts an integer value in the range of 0 to 127 (8-bit encoding) into a single-character-length
charstring value. The integer value describes the 8-bit encoding of the character.
In addition to the general error causes in clause 16.1.2, error causes are:
• invalue is less than 0 or greater than 127.

Add builtin function int2char

---

builtins/builtins.go
interpreter/interpreter_test.go
runtime/object.go

I'm trying to implement two new build-in functions:
**there is an issue: both should use 'unversal charstring' which does not exist! there is no **runtime.UniCharstring****
Please provide some ideas on how to progress with this commit.
unichar2int
> C.1.12 Universal character to integer
>  unichar2int(in universal charstring invalue) return integer
> This function converts a single-character-length universal charstring value into an integer value in the range of
> 0 to 2 147 483 647. The integer value describes the 32-bit encoding of the character.
> In addition to the general error causes in clause 16.1.2, error causes are:
> • length of invalue does not equal 1. 
int2unichar
> C.1.2 Integer to universal character
>  int2unichar(in integer invalue) return universal charstring
> This …

unichar2int AND int2unichar

---

builtins/builtins.go
interpreter/interpreter_test.go

Adding **int2str**
C.1.7 Integer to charstring
int2str(in integer invalue) return charstring
This function converts the integer value into its string equivalent (the base of the return string is always decimal).
The general error causes in clause 16.1.2 apply.
EXAMPLE:
int2str(66) // will return the charstring value "66"
int2str(-66) // will return the charstring value "-66"
int2str(0) // will return the charstring value "0"

Add int2str builtin function

---

ttcn3/v2/printer/printer.go
ttcn3/v2/printer/printer_test.go

This PR fixes following indentation issues:
Indentation handling (p.needIndent) does not work for tokens contains
newlines (e.g. preprocessor directories and comments), causing the
following tokens have to no indentation at all.
Only the first line of multi-line comments (/* foobar */) was indented
correctly, because the comment string was printed verbatim. By printing
one comment line at a time (plus one space to align the asterisks), the
indentation is as excepted.
There are known scenarios where formatting is messed up. For example:
```ttcn3
x := 1;        // foo
y := 2;        // bar
z := 345678;   /*
* blubb
*/
```
The last two lines won't be aligned, but have the same indentation as
the `z` token.

Fix indentation issues

---

ttcn3/v2/syntax/syntax_test.go

This PR adds three benchmarks for the Span-method of the syntax nodes.
The syntax three does not store line information of every node. Instead we rely on a line-map and a binary search converting file offsets to source lines.
Position heavy tools (like formatter) could benefit from a line cache. The benchmarks in this commit may assist during optimization.
Three benchmarks (with still similar performance) have been added:
* BenchmarkSpansRandomAccess accesses text spans in random order, acting as baseline for spans without cache.
* BenchmarkSpansTreeInspect accesses text spans in tree traversal order. Tree traversal order means that the begin and end positions are in many cases in different lines, which makes it harder to implement an efficient cache.
* BenchmarkSpansTokenList accesses …

Add benchmarks for Span

---

interpreter/interpreter.go
interpreter/interpreter_test.go
runtime/object.go

this is an implementation of **runtime.Enum** required for _C.1.4 Integer to enumerated_  **int2enum**

Add runtime.Enum

---

ttcn3/v2/syntax/syntax.go
ttcn3/v2/syntax/syntax_test.go

This PR fixes an endless loop of Inspect. `Next` function was using absolute event addressing, while Builder used relative event addressing.
This commit also changes the behaviour of Inspect: Calls to token will no longer be followed by a call to Nil.
Example: Tree this three nodes. Node A as root, with two children B and C. Previously Inspect executed these calls:
f(A)
f(B)
f(Nil
f(C)
f(Nil)
f(Nil)
Now, f(Nil) as only called after non-terminals:
f(A)
f(B)
f(C)
f(Nil)

Fix and modify Inspect behaviour

---

project/titan/README.md
project/titan/titan.go
project/titan/titan_gen.go

This PR adds support for TDP files (see #650).

Add schema-file for Titan descriptor files

---

builtins/builtins.go
interpreter/interpreter_test.go

int2enum ( in integer inpar, out Enumerated_type outpar)
This function converts an integer value into an enumerated value of a given enumerated type. The integer value shall be
provided as in parameter and the result of the conversion shall be stored in an out parameter. The type of the out
parameter determines the type into which the in parameter is converted.
EXAMPLE:
```
type enumerated MyFirstEnumType {
Monday, Tuesday, Wednesday, Thursday, Friday
};
type enumerated MySecondEnumType {
Saturday(-3), Sunday (0), Monday
};
// within a dynamic language element:
var MyFirstEnumType firstEnum := Tuesday;
var MySecondEnumType secondEnum := Sunday;
int2enum(0, firstEnum) // firstEnum == Monday
int2enum(1, secondEnum) // secondEnum == Monday
```

Add builtin function int2enum

---

format.go
internal/lsp/formatter.go
ttcn3/v2/printer/example_test.go
ttcn3/v2/printer/printer.go

This commit introduces a printer interface which makes it easier switch between tabs or spaces.
The format command now has a new option --tabs-to-spaces=N which will convert tabs to N spaces, if specified.
Additionally we start at indentation level -1, which is a hack to prevent module definitions being indented.

Add new printer interface

---

k3/k3r/k3r_test.go

This commit revert a test to match the old k3r version.
The test in question had been aligned with a new k3r version, which has not been released yet. Causing local tests to fail.
Until the new k3r version is released, we revert the test to match the old behavior.

Revert test to match the old k3r behavior.

---

builtins/builtins.go
interpreter/interpreter_test.go
runtime/builtins.go
runtime/object.go
ttcn3/parser/parser.go

Until we have proper semantic analysis, we need to check the arguments of builtin functions explicitly. This commit allows us to specify formal parameters for builtin functions. When formal parameters are available, the function arguments will be checked against them.
This initial implementation is only rudimentary.
Additional changes:
* the new functionality to the existing builtins.
* update tests for handle modified error messages.
* allow integers in `runtime.NewInt`.
* add support for `any` type.

Check arguments when calling builtin functions

---

builtins/builtins.go
interpreter/interpreter_test.go
runtime/builtins.go
runtime/helper_test.go
runtime/object.go
runtime/runtime.go
runtime/runtime_test.go

Most boilerplate was slightly different in each builtin test. This commit merges all builtin tests into one single table-driven test.
This commit also moves tests for argument handling into a separate file.

Simplify interpreter tests

---

builtins/builtins.go
builtins/match.go
builtins/match_test.go
interpreter/interpreter.go
interpreter/interpreter_test.go
runtime/builtins.go
runtime/object.go

This commit merges the types String and UniversalString into a single charstring type.
A TTCN-3 charstring is just a subtype of universal charstring. Merging those types simplifies our code and makes it easier to react to future charstring changes.

Merge charstring and universal charstring types

---

builtins/builtins.go
interpreter/interpreter_test.go

This function converts a charstring representing an integer value to the equivalent integer.
In addition to the general error causes in clause 16.1.2, error causes are:
• invalue contains characters other than "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" and "-".
• invalue contains the character "-" at another position than the leftmost one.
EXAMPLE:
str2int("66") // will return the integer value 66
str2int("-66") // will return the integer value -66
str2int("6-6") // will cause an erro

Add builtin function str2int

---

builtins/builtins.go
interpreter/interpreter_test.go

This function converts a charstring comprising a number into a float value. The format of the number in the
charstring shall follow rules in clause 6.1.0, items a) or b) with the following exceptions:
• leading zeros are allowed;
• leading "+" sign before positive values is allowed;
• "-0.0" is allowed;
• no numbers after the dot in the decimal notation are allowed.
In addition to the general error causes in clause 16.1.2, error causes are:
• the format of invalue is different than defined above.
EXAMPLE:
str2float("12345.6") // is the same as str2float("123.456E+02")
str2float("1.6") // returns a float value equal to 1.

Add builtin function str2float

---

lint.go

This commit fixes an incorrect lint error on nested select/case statements.
Closes #688

Fix lint error on nested select/case statements

---

k3/k3r/k3r.go
main.go
run.go
tests/tests.go

k3r stderr messages are forwarded to ntt run as debug messages.

Add LogEvent

---

.goreleaser.yml

The release procedure failed due to deprecated `replacements` field inside `.goreleaser.yml`

delete deprecated fields from .goreleaser.yml

---

internal/lsp/completion.go
internal/lsp/completion_test.go
ttcn3/tree.go

- Fields autocompletion
- Function named parameters autocompletion
- Composite Literals properties autocompletion
- Local variables autocompletion

Improve autocompletion

---

ttcn3/syntax/scanner.go
ttcn3/syntax/scanner_test.go

Currently, parsing a multiline string literal that ends with a single terminal quote on the last line results in an error:
```
foo := "multiline
string
literal
"
```

Fix parsing of multiline string literals
