nokia/ntt

ttcn3/syntax/parser.go
Type parametrization requires a backtracking parser. This commit changes how tokens are handled:
* Add input buffer for unlimited look-ahead
* Add methods for rewinding input-stream 
* Remove comment-handling temporarily. 
Note, the current token variable `p.tok` is now replaced with wrapper-functions `p.peek(1).Tok`. This is quite a waste of CPU time and will be optimized later.
=> Token queue

ttcn3/syntax/parser.go
=> Add initial preproc support

cmd/k3/list.go
List modules, imports or tests. The list command without any explicit
sub-commands will output tests.
List will not output objects from imported directories. If you need to list all
objects from a testsuite you currently have to pass .ttcn3 files as arguments.
Example:
k3 list $(k3 show -- sources) $(find $(k3 show -- imports) -name \*.ttcn3)
You can use regular expressions to filter objects. If you pass multiple regular
expressions, all of them must match (AND). Example:
$ cat example.ttcn3
testcase foo() ...
testcase bar() ...
testcase foobar() ...
...
$ k3 list --regex=foo --regex=bar
example.foobar
$ k3 list --regex='foo|bar'
example.foo
example.bar
example.foobar
Similarly, you can also specify regular expressions for documentation tags.
Example:
$ cat example.ttcn3
// @one
// @two …
=> Filter list by regular expression

internal/ntt/env.go
=> Fix #98: Variables not found when empty

internal/ntt/ntt.go
@kamil1b spotted a quite ugly piece of code.
This PR cleans it up.
=> Clean up cache function

cmd/k3-mcov/main.go
Some runtime log events are to big to fit into the buffer of `bufio.Scanner`. In this PR I'll use a `bufio.Reader` to also support very long lines.
=> [k3-mcov] Support very long lines

CONTRIBUTING.md, README.md
README.md does not contain useful information about this project and contribution guide is missing.
=> Improve contribution

internal/ntt/env.go, internal/ntt/env_test.go, internal/ntt/manifest.go
=> Initial commit of variables section

editors.md
Fix the link of vim-lsp repository
=> Fix vim-lsp link

cmake/FindNTT.cmake, examples/cmake/CMakeLists.txt, examples/cmake/Example/Example.ttcn3, examples/cmake/README.md, examples/cmake/suite1/CMakeLists.txt, examples/cmake/suite1/test.ttcn3, examples/cmake/suite2/CMakeLists.txt, examples/cmake/suite2/test.ttcn3, internal/suites/suites.go
=> Add support for ttcn3_suites.json

internal/fs/file.go, internal/fs/fs.go, internal/fs/store.go, internal/lsp/commands.go, internal/ntt/manifest.go, internal/ntt/ntt.go, project/project.go
This PR fixes a regression introduces by Project package.
=> Fix url issue

go.mod, go.sum, internal/cmds/dump/main.go
This PR replaces the JSON formatted output of dump command with a custom format. This custom format displays more relevant data and make it easier to debug parser issues.
=> Improve dump command

internal/ttcn3/printer/printer.go
Early version of Pretty Printer:
Indents, newlines and spaces format the input code.
=> Add unusable printer

internal/ttcn3/printer/printer.go
=> Add separator printer

cmd/ntt/main.go, internal/cmds/run/main.go, ttcn3/ttcn3.go
=> Add run command

internal/ntt/manifest.go
=> Use absolute path for suite name calculation

internal/ntt/manifest.go
=> Ignore NTT_CACHE for ./package.yml

internal/cmds/build/main.go, internal/cmds/build/main_test.go
This PR adds some additional tests for import handling.
Building adapters and ASN.1 codecs will be covered in a follow-up commit.
=> Add build tests

cmd/ntt/main.go, cmd/ntt/run.go, k3/run/run.go
* Trim K3RFLAGS
* Log k3 runtime exit event
* Add missing --tests-file flag
=> Various fixes

builtins/match_test.go
=> Add more Float tests

builtins/match_test.go
Test if match function can correctly match Verdicts.
=> Add Verdict Tests

builtins/match.go, builtins/match_test.go, runtime/object.go
=> Set of tests

internal/run/run.go, k3/k3r/k3r.go, k3/k3r/k3r_test.go, project/project.go, project/project_test.go, run.go, tests/runner/runner.go, tests/tests.go
Current ntt run implementation is mostly a transcript of the Nokia internal bash script k3-run. Accordingly is does not have a good structure or good test coverage.
This commit introduces some structure and initials tests for the ntt run command.
=> Refactor run

CONTRIBUTING.md
Was reading through the the docs on contributing and noticed some grammar mistakes. Felt like a good place to start contributing if I can. 
The change is simply improving the readability of the first sentence in the 'A Pull Request Workflow'.
=> fixing some grammar in the 'A Pull Request Workflow'

ttcn3/token/token.go, ttcn3/v2/printer/printer.go, ttcn3/v2/printer/printer_test.go, ttcn3/v2/syntax/syntax.go
This PR introduces a new pretty printer, which already uses the new TTCN-3 package and is also easier to use.
=> Add pretty printer v2

ttcn3/v2/printer/printer.go, ttcn3/v2/printer/printer_test.go
This PR introduces an API which uses io.Writer interface and thus is more flexible.
=> Change printer API

ttcn3/v2/printer/example_test.go, ttcn3/v2/printer/printer.go, ttcn3/v2/printer/printer_test.go
This PR aligns assignments and comments.
Due to its refactoring it also closes #641
=> Add alignment rules

internal/lsp/general.go
This PR just fixes two malformed struct tags
=> Fix malformed struct tags

k3/k3r/k3r.go
… EV GDB_SERVER with the 'com' params of the gdbserver command
=> attach gdbserver to runtime process

run.go
This commit removes the k3s backend from the run command. Removing the backend makes refactoring and paying down technical debt easier.
The k3s backend was used by the language server to run tests from within the IDE. This functionality should also work without k3s. If it doesn't, it should be easy to re-add the k3s backend.
=> Remove k3s backend

interpreter/interpreter.go, interpreter/interpreter_test.go, runtime/object.go
this im my attempt to handle Value Declarations for Enums:
```
type enumerated EB {red(0..10)}; var EB v := red(1); v
type enumerated EC {red(0..10), blue}; var EC v := blue; v;
```
please comment and share ideas.
=> enum ValueDecl

lint.go
Add definition checking for set, enum, union, record
=> Add definition checking for set, enum, union, record
